services:
  freesurfer:
    image: freesurfer/freesurfer:7.4.1
    container_name: freesurfer
    user: root
    volumes:
      - ${O_PATH}:/data
      - $FS_LICENSE_PATH:/usr/local/freesurfer/.license
    command: /bin/bash

  ants:
    image: antsx/ants:latest
    container_name: ants
    user: root
    volumes:
      - ${O_PATH}:/data
    command: /bin/bash

  neurocbir:
    image: neurocbir:latest
    container_name: neurocbir
    user: root
    volumes:
      - ${O_PATH}:/data
      - ../configs:/configs
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
