# >>> USER CONFIGURATION — You can modify these values <<<
img_path: "data/data_private/example/OAS30001_MR_d0129/mri/align_norm.nii.gz" # Path to MRI image to query
seg_path: "data/data_private/example/OAS30001_MR_d0129/mri/align_aparc+aseg.nii.gz" # (only region) Path to MRI image to query
o_path: "" # Path to save neurocbir report. If None then it is not saved.
labels_path: "data/labels.csv" # (only region)
bb_path: "data/bounding_boxes.csv" # (only region)
scope: "region" # Scope of the query: "whole-brain" or "region"
region: "Left-Hippocampus" # (only region) Region name — Required if scope == "region"
whole_brain:
  emb_dataset_path: "data/data_private/whole_brain/projected_embeddings.parquet" # Path to the embedding dataset
region:
  emb_dataset_path: "data/data_private/region_brain/projected_embeddings.parquet" # Path to the embedding dataset
top_k: 25 # Number of top results to retrieve
device: "cpu" # Device to use: "cpu" or "cuda"