version: "3.9"

services:
  fastsurfer:
    image: deepmi/fastsurfer:cpu-v2.4.2
    container_name: fastsurfer
    environment:
      - FS_LICENSE=/data/fs_license.txt
    volumes:
      - ./data:/data
    command: /bin/bash

  neurocbir:
    build:
      context: ../docker
      dockerfile: Dockerfile
    container_name: neurocbir
    depends_on:
      - fastsurfer
    volumes:
      - ../data:/data
      - ../configs:/configs
      - ../app:/app
    entrypoint: ["/app/entrypoint.sh"]
    command: ["--config", "/configs/default.yaml"]
