services:
  freesurfer:
    build:
      context: ../../
      dockerfile: freesurfer/freesurfer:7.4.1
    container_name: freesurfer
    user: root
    volumes:
      - ${OUT_PATH}:/data
      - $(FS_LICENSE_PATH):/usr/local/freesurfer/.license
    command: /bin/bash

  ants:
    image: antsx/ants:latest
    container_name: ants
    user: root
    volumes:
      - ${OUT_PATH}:/data
    command: /bin/bash

  neurocbir:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    container_name: neurocbir
    user: root
    volumes:
      - ${OUT_PATH}:/data
      - ../configs:/configs
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
